### ISSUE TITLE
cjs default

### ISSUE THREAD

**Issue by TrySound** [eventualbuddha/rollup-plugin-multi-entry#2]
Look at your cjs output
```
exports.entry = entry;
exports['default'] = multiEntry;
```
Seems like cjs format is not quite correct.

**Comment by eventualbuddha** [comment]
That's just what happens when you do a default export and a named export. I figured it's not really a big deal since it's always going to be imported by rollup using ES modules anyway.

**Comment by TrySound** [comment]
@eventualbuddha I don't use config. Just plain js with gulp.

**Comment by eventualbuddha** [comment]
You could always [use babel in your gulpfile](https://markgoodyear.com/2015/06/using-es6-with-gulp/).

**Comment by TrySound** [comment]
I use `gulpfile.buble.js` :))
