### ISSUE TITLE
glob order

### ISSUE THREAD

**Issue by TrySound** [eventualbuddha/rollup-plugin-multi-entry#3]
Would be great to strict order of files like gulp do this
```js
entry: ['src/*.mdl.js', 'src/*.js']
```
In this case first will be all `*.mdl.js` files and then all matched to `src/*.js` and not `*.mdl.js`

**Comment by TrySound** [comment]
[multi-glob](https://github.com/busterjs/multi-glob) works fine with it.

**Comment by eventualbuddha** [comment]
Can you create a failing test case for this? I don't see why it wouldn't work.

**Comment by TrySound** [comment]
Hm.. it works.
